site_name: kotti_file
site_description: File attachment add-on for Kotti CMS
site_url: https://disko.github.io/kotti_file/
repo_url: https://github.com/disko/kotti_file
repo_name: disko/kotti_file

theme:
  name: material

nav:
  - Home: index.md
